package com.example.step;

public enum Step {
    INPUTS, OUTPUTS, BENEFIT, SEARCH, BACKTOMENU,
    NAXD, PLASTIK, NAXDIN, PLASTIKIN, TOTALAMOUNTINPUTS,
    TOTALAMOUNTOUTPUTS, RESIDUAL, COUNT, ADMIN, START, MAIN,
    PHONE, PASSWORD, CHECKPASSWORD, TRUE, PUTDATE, ADDPATIENT,

    PATIENTNAMESURNAME, PATIENTPHONE, SEARCHPATIENT, PATIENTFLOOR,

    PATIENTATART, PATIENTFULLNAME, PATIENTHOUSE, GETACCOUNTENTFULLNAME,
    GETACCOUNTENTPHONE, GETACCOUNTENTPASSWORD, DELETEDPATIENT, PATIENYEXCEL, GETNURSEFULLNAME, GETNURSEID, GETACCOUNTENTID, GETNURSEPHONE, GETNURSEPASSWORD, SEARCHDAYNAXD, SEARCHDAYPLASTIK, SEARCHDAYTOTAL, LISTPATIENT,

}
