package com.example.step;

public enum Step {
    INPUTS, OUTPUTS, BENEFIT, SEARCH, BACKTOMENU,
    NAXD, PLASTIK, NAXDIN, PLASTIKIN, TOTALAMOUNTINPUTS,
    TOTALAMOUNTOUTPUTS, RESIDUAL, COUNT, ADMIN, START, MAIN,
    PHONE, PASSWORD, CHECKPASSWORD,
    ADDPATIENT, NURSEMENU, PATIENTADD, ENTERNAMEPATIENT, ENTERSURNAMEPATIENT,
    ENTERPHONEPATIENT, ENTERHOUSEPATIENT, ENTERFLOORPATIENT, FINISHEDADDPATIENT,
    SEARCHPATIENT, SEARCHPATIENTID, SEARCHNAMEPATIENT,
    SEARCHSURNAMEPATIENT, DELETEDPATIENT, DELETEDBYIDPATIENT, TRUE, PUTDATE, PATIENTLIST
}
